export const alternatives: Array<string> = [
    '1st place',
    '2nd place',
    '5 kills',
    'Activates contract',
    'Bunny hop',
    'Camping',
    'Collects free loadout',
    'Completes self revive',
    'Disables a vehicle',
    'Down someone mid-air',
    'Downed mid-air',
    'Downtown ending',
    'Drives vehicle',
    'Gas mask animation',
    'Gets vehicle splat',
    'Lethal equipment kill',
    'Meta kill',
    'Off meta kill',
    'Opens or closes door',
    'Pops dead silence',
    'Pops munitions',
    'Pops plate box',
    'Prison ending',
    'Roze skin',
    'Slide cancel',
    "Steals someone's vehicle",
    'Uses buy station',
    'Uses killstreak',
    'Uses parachute',
    'Uses zipline',
    'Vehicle gets disabled',
    'Vehicle gets stolen',
    "YY'ing",
];

export function getRandomBingoBoard(): Array<string> {
    const random = alternatives.sort(() => 0.5 - Math.random()).slice(0, 25);
    return random;
}
